name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    name: Auto Approve PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'chanyou0311'
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}